temp_django/temp_learn/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns=[
    url(r'^$', views.index, name = 'name'),
    url(r'^other/', views.other , name ='other'),
    url(r'^relative/', views.relative, name = 'relative'),

]

temp_django/temp_learn/temp_learn/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name = 'index' ),
    url(r'^basic_app/', include('basic_app.urls') ),
    path('admin/', admin.site.urls),
]

temp_django/temp_learn/basic_app/models.py
from django.db import models

# Create your models here.

temp_django/temp_learn/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': 'Hello world this text form context_dic in view.py', 'number':100 }
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative.html')

temp_django/temp_learn/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <ul class="navbar-nav">
          <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a><li>
        </ul>
    </div>
    </nav>

    <div class="container-fluid">

      {%block body_block%}
      {%endblock%}

    </div>

  </body>
</html>

temp_django/temp_learn/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome Index Page</h1>
    <a href="{% url 'basic_app:relative' %}">The relative</a>
    <h2> {{ text|title }} </h2>
    <h2> {{ text|cut:'world' }} </h2>
    <h2>{{ number|add:'900' }}</h2>
  {% endblock %}

temp_django/temp_learn/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>new other</h1>
    <a href="{% url 'basic_app:relative' %}">The relative</a>
  {% endblock %}

temp_django/temp_learn/templates/basic_app/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Relative</h1>
    <a href="{% url 'basic_app:other' %}">The temp other</a>
    <a href="{% url 'admin:index' %}">admin</a>
    <a href="{% url 'index' %}">Home</a>
  </body>
</html>